# Generated by Django 4.1.7 on 2023-06-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_profile_countries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='countries',
            new_name='country',
        ),
    ]
