# Generated by Django 4.1.7 on 2023-06-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_blog_blogsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='audience',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blogIdea',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
