# Generated by Django 4.1.7 on 2023-06-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_blog_audience_blog_blogidea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogsection',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
