# Generated by Django 4.1.7 on 2023-06-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_blogsection_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogsection',
            name='wordCount',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
