# Generated by Django 4.1.7 on 2023-06-28 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_blogsection_wordcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='monthlyCount',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriptionReference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='subscriptionType',
            field=models.CharField(choices=[('free', 'free'), ('starter', 'starter'), ('advance', 'advance')], default='free', max_length=100),
        ),
    ]
